### ISSUE TITLE
1.0.3 upgrade not working on RPi4 LE 10

### ISSUE THREAD

**Issue by ebym** [sbroenne/plugin.video.nhkworldtv#24]
Yesterday i upgraded to 1.0.3, afterwards NHK not working on RPi4 LibreElec 10. Anyone else having this problem ?. I have rebooted the system.

[logs here](https://pastebin.com/SxCYez7M)

**Comment by sbroenne** [comment]
Thanks for reporting this issue. 

This is actually not caused by the new version 1.0.3. but by a major version upgrade of  [script.module.tzlocal](https://mirrors.kodi.tv/addons/matrix/script.module.tzlocal/) from **v2** to **v3** that happened at the same time - see the [PR](https://github.com/xbmc/repo-scripts/pull/2122) 

Unfortunately, this update is is broken for Python 3.6 to 3.8 since it requires another module called backports.tzinfo package that is not part of Kodi repo nor is it referenced by tzlocal.

I will temporarily disable all the functionality that uses tzlocal and release a new version 1.0.4 shortly.

**Comment by sbroenne** [comment]
@ebym, v1.0.4 has been uploaded to the repo. You should be able to use the plug-in again.

**Comment by ebym** [comment]
@sbroenne Wow, that was fast, working as usual. Thank you very much.
